var buttonColors = ["red", "blue", "green", "yellow"]; // Corrected variable name to camelCase
var gamePattern = []; // Sequence generated by the game
var userClickedPattern = []; // Sequence clicked by the user

var started = false; // Flag to check if the game has started
var level = 0; // Current level

// Function to start the game on keypress or touchstart
function startGame() {
  if (!started) {
    $("#level-title").text("Level " + level); // Update level title
    nextSequence(); // Generate the first sequence
    started = true; // Set game started to true
    console.log("Game started");
  }
}

// Detect when a key is pressed to start the game
$(document).keypress(startGame);

// Detect screen touch to start the game
$(document).on("touchstart", startGame);

// Detect button clicks or touches
$(".btn").on("click touchstart", function() {
  var userChosenColor = $(this).attr("id"); // Get the id (color) of the clicked button
  userClickedPattern.push(userChosenColor); // Add the color to the user's sequence

  playSound(userChosenColor); // Play the sound for the clicked color
  animatePress(userChosenColor); // Animate the button press

  checkAnswer(userClickedPattern.length - 1); // Check the user's answer
});

// Function to check the user's answer
function checkAnswer(currentLevel) {
  if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {
    console.log("success");

    if (userClickedPattern.length === gamePattern.length) {
      setTimeout(function() {
        nextSequence();
      }, 1000);
    }
  } else {
    console.log("wrong");
    playSound("wrong");
    $("body").addClass("game-over");
    $("#level-title").text("Game Over, Press Any Key or Touch to Restart");

    setTimeout(function() {
      $("body").removeClass("game-over");
    }, 200);

    startOver();
  }
}

// Function to generate the next sequence
function nextSequence() {
  userClickedPattern = []; // Reset user's sequence
  level++; // Increment level
  $("#level-title").text("Level " + level); // Update level title

  var randomNumber = Math.floor(Math.random() * 4); // Generate a random number between 0 and 3
  var randomChosenColor = buttonColors[randomNumber]; // Select a random color
  gamePattern.push(randomChosenColor); // Add the color to the game's sequence

  $("#" + randomChosenColor).fadeIn(100).fadeOut(100).fadeIn(100); // Animate the button
  playSound(randomChosenColor); // Play the sound for the color

  console.log("Next sequence: " + gamePattern);
}

// Function to animate button press
function animatePress(currentColor) {
  $("#" + currentColor).addClass("pressed");
  setTimeout(function() {
    $("#" + currentColor).removeClass("pressed");
  }, 100);
}

// Function to play sound
function playSound(name) {
  var audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}

// Function to start over the game
function startOver() {
  level = 0;
  gamePattern = [];
  started = false;
  console.log("Game restarted");
}
